# Generated by Django 4.0.4 on 2022-05-21 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_slot', models.IntegerField(blank=True, choices=[(1, '8:00-8:30'), (2, '8:45-9:15'), (3, '9:30-10:00'), (4, '10:15-10:45'), (5, '11:00-11:30'), (6, '11:45-12:15'), (7, '12:30-1:00'), (8, '2:00-2:30'), (9, '2:45-3:15'), (10, '3:30-4:00'), (11, '4:15-4:45'), (12, '5:00-5:30')], null=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'db_table': 'appointments',
            },
        ),
    ]
